name: gym_log
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.1
  csv: ^6.0.0
  excel: ^4.0.6
  file_picker: 8.1.4
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_crashlytics: ^4.3.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  open_file: ^3.5.10
  path_provider: ^2.1.5
  popover: ^0.3.1
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.svg
    - assets/gym_log_logo.svg
    - assets/gym_log_horizontal_logo.svg
