name: gym_log
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_ui_auth: ^1.16.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^21.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
