// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBawR3yRZPpGQODbQFlRUO-IUodzuTlnao',
    appId: '1:255044437319:android:ed34f6e31a4fa5f856f862',
    messagingSenderId: '255044437319',
    projectId: 'gym-log-2e57a',
    storageBucket: 'gym-log-2e57a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_IdZQtNwCOsYNJNL3DsmNSL4dJp7YHk',
    appId: '1:255044437319:ios:6f4c46374c2b9c9256f862',
    messagingSenderId: '255044437319',
    projectId: 'gym-log-2e57a',
    storageBucket: 'gym-log-2e57a.firebasestorage.app',
    androidClientId: '255044437319-2soo1b3oh7elhvq844t05jf44cnjg5jl.apps.googleusercontent.com',
    iosClientId: '255044437319-h135n9uj221nnfk46pk5q3eh68amspa7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymLog',
  );

}